//------------------------------------------------------------------------------
// <auto-generated>
//     Цей код було авто-згенеровано com.unity.inputsystem:InputActionCodeGenerator
//     версія 1.19.0
//     з Assets/Scripts/CameraAction.inputactions
//
//     Зміни в цьому файлі можуть спричинити некоректну поведінку і будуть втрачені
//     при повторній генерації коду.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Надає програмний доступ до екземплярів <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> та <see cref="InputControlScheme" />, визначених у асеті "Assets/Scripts/CameraAction.inputactions".
/// </summary>
/// <remarks>
/// Цей клас згенеровано з вихідного коду, і будь-які ручні зміни будуть відхилені при повторному імпорті або модифікації пов'язаного асету.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Приклад використання InputActionMap з іменем "Player" з UnityEngine.MonoBehaviour, що реалізує інтерфейс зворотного виклику.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Представлення асету у вихідному коді.
///     private MyActions_Actions.PlayerActions m_Player;     // Представлення карти дій у вихідному коді.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Створення об'єкта асету.
///         m_Player = m_Actions.Player;                      // Отримання об'єкта карти дій.
///         m_Player.AddCallbacks(this);                      // Реєстрація інтерфейсу зворотного виклику IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Знищення об'єкта асету.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Увімкнення всіх дій у карті.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Вимкнення всіх дій у карті.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Викликається, коли дія "Move" запускається, виконується або скасовується.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Викликається, коли дія "Attack" запускається, виконується або скасовується.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @CameraAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Надає доступ до базового екземпляра асету.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Створює новий екземпляр.
    /// </summary>
    public @CameraAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""CameraAction"",
    ""maps"": [
        {
            ""name"": ""MoveCamera"",
            ""id"": ""5a08f976-cc8d-4749-acd6-2b4ade9993dd"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""7076a50d-1f9a-41c5-9e8c-71281e2b3d8b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""f8e0efe3-4c22-4cd5-8ec7-80a02103334d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateMouse"",
                    ""type"": ""Value"",
                    ""id"": ""e6884806-b9e4-4bbe-89de-fbe8ae1e510b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""c46fabb0-9168-4135-938b-4e51771d5274"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""db91c2b1-83c5-468c-b27d-9e0f8e6f2094"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""07ea3a1e-28df-45cd-bbc5-2225a3aeaa15"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c5e29b30-586b-42da-910b-522138fac894"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6c2e9dad-080f-41f5-bbc8-fd28fe97213a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""832df79e-28d7-498a-965c-0f6985914406"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""803119a9-3e49-49f2-b854-2a8c42ada27c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3f0dbdaf-fce1-4947-bacc-2ef463337f24"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f8184b30-8210-493f-8793-2ab117181f29"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5ba6772e-6cc6-4f96-b8fa-fb9a3e84b66b"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f6b2199-65a9-4490-be56-9570a88925b7"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Карта дій MoveCamera
        m_MoveCamera = asset.FindActionMap("MoveCamera", throwIfNotFound: true);
        m_MoveCamera_Move = m_MoveCamera.FindAction("Move", throwIfNotFound: true);
        m_MoveCamera_Rotate = m_MoveCamera.FindAction("Rotate", throwIfNotFound: true);
        m_MoveCamera_RotateMouse = m_MoveCamera.FindAction("RotateMouse", throwIfNotFound: true);
        m_MoveCamera_Zoom = m_MoveCamera.FindAction("Zoom", throwIfNotFound: true);
    }

    ~@CameraAction()
    {
        UnityEngine.Debug.Assert(!m_MoveCamera.enabled, "This will cause a leak and performance issues, CameraAction.MoveCamera.Disable() has not been called.");
    }

    /// <summary>
    /// Знищує цей асет та всі пов'язані екземпляри <see cref="InputAction"/>.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Карта дій MoveCamera
    private readonly InputActionMap m_MoveCamera;
    private List<IMoveCameraActions> m_MoveCameraActionsCallbackInterfaces = new List<IMoveCameraActions>();
    private readonly InputAction m_MoveCamera_Move;
    private readonly InputAction m_MoveCamera_Rotate;
    private readonly InputAction m_MoveCamera_RotateMouse;
    private readonly InputAction m_MoveCamera_Zoom;
    /// <summary>
    /// Надає доступ до вхідних дій, визначених у карті вхідних дій "MoveCamera".
    /// </summary>
    public struct MoveCameraActions
    {
        private @CameraAction m_Wrapper;

        /// <summary>
        /// Створює новий екземпляр класу-обгортки карти вхідних дій.
        /// </summary>
        public MoveCameraActions(@CameraAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Надає доступ до базової вхідної дії "MoveCamera/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_MoveCamera_Move;
        /// <summary>
        /// Надає доступ до базової вхідної дії "MoveCamera/Rotate".
        /// </summary>
        public InputAction @Rotate => m_Wrapper.m_MoveCamera_Rotate;
        /// <summary>
        /// Надає доступ до базової вхідної дії "MoveCamera/RotateMouse".
        /// </summary>
        public InputAction @RotateMouse => m_Wrapper.m_MoveCamera_RotateMouse;
        /// <summary>
        /// Надає доступ до базової вхідної дії "MoveCamera/Zoom".
        /// </summary>
        public InputAction @Zoom => m_Wrapper.m_MoveCamera_Zoom;
        /// <summary>
        /// Надає доступ до базового екземпляра карти вхідних дій.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MoveCamera; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Неявно перетворює <see ref="MoveCameraActions" /> на екземпляр <see ref="InputActionMap" />.
        /// </summary>
        public static implicit operator InputActionMap(MoveCameraActions set) { return set.Get(); }
        /// <summary>
        /// Додає зворотні виклики <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> та <see cref="InputAction.canceled"/>, надані через <param cref="instance" />, для всіх вхідних дій у цій карті.
        /// </summary>
        /// <param name="instance">Екземпляр зворотного виклику.</param>
        /// <remarks>
        /// Якщо <paramref name="instance" /> є <c>null</c> або <paramref name="instance"/> вже було додано, цей метод нічого не робить.
        /// </remarks>
        /// <seealso cref="MoveCameraActions" />
        public void AddCallbacks(IMoveCameraActions instance)
        {
            if (instance == null || m_Wrapper.m_MoveCameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MoveCameraActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @RotateMouse.started += instance.OnRotateMouse;
            @RotateMouse.performed += instance.OnRotateMouse;
            @RotateMouse.canceled += instance.OnRotateMouse;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
        }

        /// <summary>
        /// Видаляє зворотні виклики <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> та <see cref="InputAction.canceled"/>, надані через <param cref="instance" />, для всіх вхідних дій у цій карті.
        /// </summary>
        /// <remarks>
        /// Виклик цього методу, коли <paramref name="instance" /> не було попередньо зареєстровано, не має побічних ефектів.
        /// </remarks>
        /// <seealso cref="MoveCameraActions" />
        private void UnregisterCallbacks(IMoveCameraActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @RotateMouse.started -= instance.OnRotateMouse;
            @RotateMouse.performed -= instance.OnRotateMouse;
            @RotateMouse.canceled -= instance.OnRotateMouse;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
        }

        /// <summary>
        /// Скасовує реєстрацію <param cref="instance" /> та скасовує всі зворотні виклики вхідних дій через <see cref="MoveCameraActions.UnregisterCallbacks(IMoveCameraActions)" />.
        /// </summary>
        /// <seealso cref="MoveCameraActions.UnregisterCallbacks(IMoveCameraActions)" />
        public void RemoveCallbacks(IMoveCameraActions instance)
        {
            if (m_Wrapper.m_MoveCameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Замінює всі існуючі екземпляри зворотних викликів та пов'язані з ними раніше зареєстровані зворотні виклики вхідних дій на зворотні виклики, надані через <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// Якщо <paramref name="instance" /> є <c>null</c>, виклик цього методу лише скасує реєстрацію всіх існуючих зворотних викликів, але не зареєструє нових.
        /// </remarks>
        /// <seealso cref="MoveCameraActions.AddCallbacks(IMoveCameraActions)" />
        /// <seealso cref="MoveCameraActions.RemoveCallbacks(IMoveCameraActions)" />
        /// <seealso cref="MoveCameraActions.UnregisterCallbacks(IMoveCameraActions)" />
        public void SetCallbacks(IMoveCameraActions instance)
        {
            foreach (var item in m_Wrapper.m_MoveCameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MoveCameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Надає новий екземпляр <see cref="MoveCameraActions" />, що посилається на цю карту дій.
    /// </summary>
    public MoveCameraActions @MoveCamera => new MoveCameraActions(this);
    /// <summary>
    /// Інтерфейс для реалізації методів зворотного виклику для всіх зворотних викликів вхідних дій, пов'язаних з діями, визначеними "MoveCamera", що дозволяє додавати та видаляти зворотні виклики.
    /// </summary>
    /// <seealso cref="MoveCameraActions.AddCallbacks(IMoveCameraActions)" />
    /// <seealso cref="MoveCameraActions.RemoveCallbacks(IMoveCameraActions)" />
    public interface IMoveCameraActions
    {
        /// <summary>
        /// Метод, що викликається, коли пов'язана вхідна дія "Move" є <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> або <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Метод, що викликається, коли пов'язана вхідна дія "Rotate" є <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> або <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotate(InputAction.CallbackContext context);
        /// <summary>
        /// Метод, що викликається, коли пов'язана вхідна дія "RotateMouse" є <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> або <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateMouse(InputAction.CallbackContext context);
        /// <summary>
        /// Метод, що викликається, коли пов'язана вхідна дія "Zoom" є <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> або <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZoom(InputAction.CallbackContext context);
    }
}
